apiVersion: apps/v1
kind: Deployment
metadata:
  name: delight-shop-deployment
  labels:
    app: delight-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delight-shop
  template:
    metadata:
      labels:
        app: delight-shop
    spec:
      containers:
      - name: frontend-app
        image: hahaha555/devops-delight-shop:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
